// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLXJEBLpJQDJRUsM44D6f1JsVaeYTuTg',
    appId: '1:362887982100:web:f38dc4bba213b06eee0b01',
    messagingSenderId: '362887982100',
    projectId: 'swiperight-ba820',
    authDomain: 'swiperight-ba820.firebaseapp.com',
    storageBucket: 'swiperight-ba820.appspot.com',
    measurementId: 'G-CVMGNVWTTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOXeYSQDbB3IXRSdrJ4FSPwMdU6RJsyJ4',
    appId: '1:362887982100:android:a9345f2d368393a2ee0b01',
    messagingSenderId: '362887982100',
    projectId: 'swiperight-ba820',
    storageBucket: 'swiperight-ba820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90R7xCX7vGSe9vv121Mi-0Xe0Y5i9NEM',
    appId: '1:362887982100:ios:fce2072bee38e5f2ee0b01',
    messagingSenderId: '362887982100',
    projectId: 'swiperight-ba820',
    storageBucket: 'swiperight-ba820.appspot.com',
    iosBundleId: 'com.example.swiperight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA90R7xCX7vGSe9vv121Mi-0Xe0Y5i9NEM',
    appId: '1:362887982100:ios:d22e15cfd2e0f285ee0b01',
    messagingSenderId: '362887982100',
    projectId: 'swiperight-ba820',
    storageBucket: 'swiperight-ba820.appspot.com',
    iosBundleId: 'com.example.swiperight.RunnerTests',
  );
}
